[[v310notes]]
JaXMPP V3.1.0 Release Notes
===========================
:author: Daniel Wisnewski (daniel@tigase.org)
:version: v1.0
:date: 21-04-2016 11:00

:toc:
:numbered:
:website: http://www.tigase.org

Tigase JaXMPP v3.1.0 has been released!  Please review the change notes below to see what has changed since our last release.

New Features
------------

- link:http://http://www.xmpp.org/extensions/xep-0202.html[XEP-0202 Entity Time] is now supported by Client Library.
- #3270 & #3732 Proxy support has been implemented to JaXMPP library.
- #3717 JaXMPP now supports retrieving whole stanza from Message Archive rather than just the <body/> element.
You will need to set +sess-man/plugins-conf/message-archive/msg-archive-paths[s]=/message/body,/message/subject+ in init.properties to enable this feature.  Here, both body and subject will be stored.

- #3749 Added support to enable access to original elements of retrieved collection from collections list within Message Archive implementation.
- link:https://projects.tigase.org/issues/4000[#4000] UTF-8 support improved to include multibyte characters.

Fixes
-----

- BOSH exception now ignored if connector is disconnected while in disconnection stage.
- Fixed NPE from +StreamManagementModule+ with not sent Elements.
- link:https://projects.tigase.org/issues/3401[#3401] Fixed NPE during check of timeout request in GWT.
- #3626 Dummy TrustManager removed for Websocket Connections, now Defaults to use Java Certificate Checker.
- #3718 Removed 'Disconnecting!!' exception from +AbstractWebSocketConnector+ which caused RuntimeException when attempting to send error stanza.
- #3831 Fixed text to byte stream error causing a drop in packets when using special characters.
- #3902 Fixed Websocket connections closing after 3 minutes of inactivity.
- #3917 Fixed error where JaXMPP would send invalid XML stanzas resulting in disconnection in rare circumstances.
- #3982 Fixed Websocket header being sent with invalid values.
- #4051 Fixed occasional NPE while processing <message> stanzas.
- link:https://projects.tigase.org/issues/4061[#4061] Fixed issue with sending errors during stream error.
- link:https://projects.tigase.org/issues/4069[#4069] Enabled proper masking of Websocket Frames and proper connection close with unmasked frames.
- link:https://projects.tigase.org/issues/4076[#4076] Fixed stream closing logic, JaXMPP now waits to receive </stream:stream> from server before closing stream.
